on:
  workflow_dispatch:
  release: 
    types: [published]
    
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Initialize npm environment
        uses: ./.github/actions/init-npm
      
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}